# Generated by Django 3.0.5 on 2020-08-19 12:45

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import tracker.enums
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('name', models.CharField(max_length=50)),
                ('water', models.IntegerField(default=0)),
                ('carbondioxide', models.IntegerField(default=0)),
                ('land', models.IntegerField(default=0)),
                ('category', enumfields.fields.EnumField(default='none', enum=tracker.enums.IngredientCategory, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_amount', to='tracker.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('name', models.CharField(max_length=50)),
                ('water_saved', models.IntegerField(default=0)),
                ('carbondioxide_saved', models.IntegerField(default=0)),
                ('land_saved', models.IntegerField(default=0)),
                ('ingredients', models.ManyToManyField(related_name='meat_ingredient', through='tracker.IngredientAmount', to='tracker.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VegIngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veg_ingredient_amount', to='tracker.Ingredient')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veg_ingredient_amount', to='tracker.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='veg_ingredients',
            field=models.ManyToManyField(related_name='veg_ingredient', through='tracker.VegIngredientAmount', to='tracker.Ingredient'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('water_saved', models.IntegerField(default=0)),
                ('carbondioxide_saved', models.IntegerField(default=0)),
                ('land_saved', models.IntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_amount', to='tracker.Recipe'),
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('water_saved', models.IntegerField(default=0)),
                ('carbondioxide_saved', models.IntegerField(default=0)),
                ('land_saved', models.IntegerField(default=0)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Company')),
                ('order', models.ManyToManyField(to='tracker.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
