# Generated by Django 3.0.5 on 2020-08-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200819_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='carbondioxide_saved',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='land_saved',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='water_saved',
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbondioxide_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbondioxide_use_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='land_saved_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='land_saved_use_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='water_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='water_use_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='order',
            field=models.ManyToManyField(related_name='company_order', to='tracker.Order'),
        ),
    ]
