# Generated by Django 3.0.5 on 2020-08-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200819_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carbondioxide_saved',
        ),
        migrations.RemoveField(
            model_name='order',
            name='land_saved',
        ),
        migrations.RemoveField(
            model_name='order',
            name='water_saved',
        ),
    ]
