# Generated by Django 3.0.5 on 2020-08-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200820_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyorder',
            name='carbondioxide_saved',
        ),
        migrations.RemoveField(
            model_name='companyorder',
            name='land_saved',
        ),
        migrations.RemoveField(
            model_name='companyorder',
            name='water_saved',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbondioxide',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='land',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='water',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbondioxide_use',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbondioxide_use_veg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='land_use',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='land_use_veg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='water_use',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='water_use_veg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
