# Generated by Django 3.0.5 on 2020-08-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200820_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='carbondioxide_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='company',
            name='land_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='company',
            name='water_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
