# Generated by Django 3.0.5 on 2020-09-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200820_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbondioxide',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='land',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='water',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
