# Generated by Django 3.0.5 on 2020-09-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200915_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_ingredient_amount', to='tracker.Ingredient')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_ingredient_amount', to='tracker.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
